// From HexaDoken.
class HDPurgeTheBarrelsPlease : Actor {
states{
	spawn:
		TNT1 A 0 nodelay {
			ThinkerIterator Purger = ThinkerIterator.Create("HDBarrel");
			Actor mo;
			int count=0;
			while (mo = HDBarrel(Purger.Next()))
				if (mo.health < 1) { mo.Destroy(); count++;} 
			if (count < 1) Console.Printf("No barrels to purge.");
			else if (count == 1) Console.Printf("Purged 1 barrel.");
			else Console.Printf("Purged %i barrels.", count);
		}
		stop;
	}
}